### ISSUE TITLE
"RuntimeError: Expected atoms table not found" when converting leaprc.ff10 to ffxml

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#1003]
I'm trying to update the OpenMM Amber forcefield conversion to use AmberTools 18 in https://github.com/choderalab/openmm-forcefields/pull/66 but am running into this error converting `leaprc.ff10`:
```
Converting /Users/choderaj/miniconda/bin/../dat/leap/cmd/oldff/leaprc.ff10 to ffxml...
Preprocessing the leaprc for ff10...
Converting to ffxml ffxml/ff10.xml...
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+54.ge824d26c-py3.6-macosx-10.9-x86_64.egg/parmed/amber/offlib.py:240: AmberWarning: Unexpected childsequence (3); expected 2 for residue SEP
  'residue %s' % (n, nres+1, name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+54.ge824d26c-py3.6-macosx-10.9-x86_64.egg/parmed/amber/offlib.py:240: AmberWarning: Unexpected childsequence (3); expected 2 for residue H2D
  'residue %s' % (n, nres+1, name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+54.ge824d26c-py3.6-macosx-10.9-x86_64.egg/parmed/amber/offlib.py:240: AmberWarning: Unexpected childsequence (3); expected 2 for residue S1P
  'residue %s' % (n, nres+1, name), AmberWarning)
Traceback (most recent call last):
  File "convert_amber.py", line 1214, in <module>
    main()
  File "convert_amber.py", line 105, in main
    convert_yaml(args.input, ffxml_dir='ffxml/')
  File "convert_amber.py", line 381, in convert_yaml
    filter_warnings=filter_warnings, split_filename=True)
  File "convert_amber.py", line 205, in convert_leaprc
    params = parmed.amber.AmberParameterSet.from_leaprc(leaprc)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+54.ge824d26c-py3.6-macosx-10.9-x86_64.egg/parmed/amber/parameters.py", line 298, in from_leaprc
    params.residues.update(AmberOFFLibrary.parse(_find_amber_file(fname, search_oldff)))
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+54.ge824d26c-py3.6-macosx-10.9-x86_64.egg/parmed/amber/offlib.py", line 138, in parse
    raise RuntimeError('Expected atoms table not found')
RuntimeError: Expected atoms table not found
```
Any idea what may have changed in parmed that would affect the conversion of this forcefield?

**Comment by swails** [comment]
I recently changed a regex in the lib file reader to make it ignore trailing spaces on one of the header lines. 

I don’t think that would cause this problem, but I haven’t touched that code in a long time outside that change (that was needed to correctly parse another file).

**Comment by jchodera** [comment]
@rafwiewiora any further ideas here?

**Comment by rafwiewiora** [comment]
So two things:

a) The problematic call in `leaprc.ff10` is `loadOff oldff/phosphoaa.10.lib` - you'll see there was a problem with this originally: 

```python
# set files that are ignored in leaprc's
# solvents and ions converted separately; leaprc.ff10 calls phosphoaa10.lib
# which does not exist anymore, LeAP skips it on error so we do too
ignore = {'solvents.lib', 'atomic_ions.lib', 'ions94.lib', 'ions91.lib',
          'phosphoaa10.lib'}
```

(https://github.com/choderalab/openmm-forcefields/blob/master/amber/convert_amber.py#L46-L50)

the previous AmberTools did `loadOff phosphoaa10.lib` and that file was simply missing, so we ignore that line. Now the file has reappeared in AmberTools 18, but in the `oldff` folder, so we're not ignoring it anymore. 

2) The file is "broken" by having an extra new line at the end - ParmEd is not accounting for this possibility here: https://github.com/ParmEd/ParmEd/blob/9f6c733fedd1a61e8bf7abe0fa8647280318adf7/parmed/amber/offlib.py#L135 - the '\n' doesn't match the regex and you get the error. 

Solutions: 

a) make https://github.com/choderalab/openmm-forcefields/blob/master/amber/convert_amber.py#L49 
```
ignore = {'solvents.lib', 'atomic_ions.lib', 'ions94.lib', 'ions91.lib','phosphoaa10.lib', `oldff/phosphoaa10.lib`}
```

b) make ParmEd account for the new line, guess you want https://github.com/ParmEd/ParmEd/blob/9f6c733fedd1a61e8bf7abe0fa8647280318adf7/parmed/amber/offlib.py#L135 to be something like `while (line and line != '\n')

**Comment by jchodera** [comment]
Verified!

We seem to be onto the next issue:
```
Converting ['/Users/choderaj/miniconda/bin/../dat/leap/parm/frcmod.ionsjc_tip3p', '/Users/choderaj/miniconda/bin/../dat/leap/parm/frcmod.ions234lm_126_tip3p', '/Users/choderaj/miniconda/bin/../dat/leap/lib/atomic_ions.lib'] to ffxml...
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+63.gc3226b8c-py3.6-macosx-10.9-x86_64.egg/parmed/openmm/parameters.py:122: UserWarning: Residue AG contains atom type Ag+ not found in parameter set and will be dropped.
  warnings.warn('Residue {} contains atom type {} not found in parameter set and will be dropped.'.format(residue.name, atom.type))
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+63.gc3226b8c-py3.6-macosx-10.9-x86_64.egg/parmed/openmm/parameters.py:122: UserWarning: Residue CU1 contains atom type Cu+ not found in parameter set and will be dropped.
  warnings.warn('Residue {} contains atom type {} not found in parameter set and will be dropped.'.format(residue.name, atom.type))
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+63.gc3226b8c-py3.6-macosx-10.9-x86_64.egg/parmed/openmm/parameters.py:122: UserWarning: Residue H3O+ contains atom type H3O+ not found in parameter set and will be dropped.
  warnings.warn('Residue {} contains atom type {} not found in parameter set and will be dropped.'.format(residue.name, atom.type))
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+63.gc3226b8c-py3.6-macosx-10.9-x86_64.egg/parmed/openmm/parameters.py:122: UserWarning: Residue HE+ contains atom type HE+ not found in parameter set and will be dropped.
  warnings.warn('Residue {} contains atom type {} not found in parameter set and will be dropped.'.format(residue.name, atom.type))
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+63.gc3226b8c-py3.6-macosx-10.9-x86_64.egg/parmed/openmm/parameters.py:122: UserWarning: Residue HZ+ contains atom type HZ+ not found in parameter set and will be dropped.
  warnings.warn('Residue {} contains atom type {} not found in parameter set and will be dropped.'.format(residue.name, atom.type))
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+63.gc3226b8c-py3.6-macosx-10.9-x86_64.egg/parmed/openmm/parameters.py:122: UserWarning: Residue NH4 contains atom type NH4+ not found in parameter set and will be dropped.
  warnings.warn('Residue {} contains atom type {} not found in parameter set and will be dropped.'.format(residue.name, atom.type))
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+63.gc3226b8c-py3.6-macosx-10.9-x86_64.egg/parmed/openmm/parameters.py:122: UserWarning: Residue TL contains atom type Tl+ not found in parameter set and will be dropped.
  warnings.warn('Residue {} contains atom type {} not found in parameter set and will be dropped.'.format(residue.name, atom.type))
Modifying converted ffxml to append solvent parameters
ffxml/tip3p_standard.xml successfully written!
Validating the conversion...
Water and ions energy validation for ffxml/tip3p_standard.xml
Preparing temporary files for validation...
Preparing LeaP scripts...
Running LEaP...
Calculating and validating energies...
Deleting temp files...
Traceback (most recent call last):
  File "convert_amber.py", line 1214, in <module>
    main()
  File "convert_amber.py", line 105, in main
    convert_yaml(args.input, ffxml_dir='ffxml/')
  File "convert_amber.py", line 416, in convert_yaml
    standard_ffxml=standard_ffxml)
  File "convert_amber.py", line 990, in validate_water_ion
    system_omm = ff.createSystem(pdb.topology)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 1109, in createSystem
    [template, matches] = self._getResidueTemplateMatches(res, bondedToAtom, ignoreExternalBonds=ignoreExternalBonds)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 885, in _getResidueTemplateMatches
    raise Exception('Multiple matching templates found for residue %d (%s): %s.' % (res.index+1, res.name, ', '.join(match[0].name for match in allMatches)))
Exception: Multiple matching templates found for residue 8 (NA): NA, Na+.
```
Any ideas @rafwiewiora? Presumably, something has changed and now we are sweeping up two sets of ions accidentally?

**Comment by swails** [comment]
Possibly because Amber used aliases to support different versions of its ion residue names? (Or at least what amounted to aliases -- may have been straight copies.)

**Comment by jchodera** [comment]
@rafwiewiora : It appears to be failing at the [first `RECIPE` in `master.yaml`](https://github.com/choderalab/openmm-forcefields/blob/2adb1a670da8521d70bd09aba8d5e38b296b5fce/amber/files/master.yaml#L318-L342):
```
MODE: RECIPE
- sourcePackage2: OpenMM
  sourcePackageVersion2: 7.2
- Source:
  - parm/frcmod.ionsjc_tip3p
  - parm/frcmod.ions234lm_126_tip3p
  - lib/atomic_ions.lib
  Solvent_source: tip3p.xml
  Solvent: tip3p
  Name: tip3p_standard
  Reference:
  - >-
    Joung, I.S., and Cheatham, Thomas E. (2008).
    Determination of Alkali and Halide Monovalent Ion Parameters for Use in Explicitly Solvated Biomolecular Simulations. J. Phys. Chem. B 112, 9020-9041.
  - >-
    Joung, I.S., and Cheatham, T.E. (2009).
    Molecular Dynamics Simulations of the Dynamic and Energetic Properties of Alkali and Halide Ions Using Water-Model-Specific Ion Parameters. J. Phys. Chem. B 113, 13279-13290.
  - >-
    Li, P., Roberts, B.P., Chakravorty, D.K., and Merz, K.M. (2013).
    Rational Design of Particle Mesh Ewald Compatible Lennard-Jones Parameters for +2 Metal Cations in Explicit Solvent. J. Chem. Theory Comput. 9, 2733-2748.
  - >-
    Jorgensen, W.L., Chandrasekhar, J., Madura, J.D., Impey, R.W., and Klein, M.L. (1983).
    Comparison of simple potential functions for simulating liquid water. The Journal of Chemical Physics 79, 926-935.
  Test:
  - water_ion
```
Should all of those files be listed as sources?

**Comment by jchodera** [comment]
We've figured this new issue out. Will post in https://github.com/choderalab/openmm-forcefields/pull/66

But the atoms table issue is now resolved!
