### ISSUE TITLE
IndexError when mixing AmberParm objects

### ISSUE THREAD

**Issue by andrrizzi** [ParmEd/ParmEd#1045]
When I run this snippet on the attached files
```python
import parmed
from simtk.openmm.app import NoCutoff
amber_parm1 = parmed.load_file('AlkEthOH_c38.top', 'AlkEthOH_c38.crd')
amber_parm2 = parmed.load_file('AlkEthOH_c1161.top', 'AlkEthOH_c1161.crd')
amber_parm_merged = amber_parm1 + amber_parm2

print('c38 LJ radius:', amber_parm1.LJ_radius)
print('c1161 LJ radius:', amber_parm2.LJ_radius)
print('merged LJ radius:', amber_parm_merged.LJ_radius, '\n')

amber_parm_merged.createSystem(nonbondedCutoff=NoCutoff)
```
I get
```
c38 LJ radius: [1.9080000000152688, 1.4869999997254757]
c1161 LJ radius: [1.9080000000152688, 1.6836999998645996, 1.4869999997254757, 1.3869999991698632, 1.286999999767076]
merged LJ radius: [1.9080000000152688, 1.4869999997254757]

Traceback (most recent call last):
  File "temp.py", line 71, in <module>
    print(amber_parm_merged.createSystem(nonbondedCutoff=NoCutoff))
  File "/Users/andrea/miniconda/envs/openforcefield/lib/python3.6/site-packages/parmed/utils/decorators.py", line 31, in new_fcn
    return fcn(*args, **kwargs)
  File "/Users/andrea/miniconda/envs/openforcefield/lib/python3.6/site-packages/parmed/structure.py", line 2074, in createSystem
    ewaldErrorTolerance, rf_dielc)
  File "/Users/andrea/miniconda/envs/openforcefield/lib/python3.6/site-packages/parmed/utils/decorators.py", line 31, in new_fcn
    return fcn(*args, **kwargs)
  File "/Users/andrea/miniconda/envs/openforcefield/lib/python3.6/site-packages/parmed/amber/_amberparm.py", line 1003, in omm_nonbonded_force
    ewaldErrorTolerance, reactionFieldDielectric
  File "/Users/andrea/miniconda/envs/openforcefield/lib/python3.6/site-packages/parmed/utils/decorators.py", line 31, in new_fcn
    return fcn(*args, **kwargs)
  File "/Users/andrea/miniconda/envs/openforcefield/lib/python3.6/site-packages/parmed/structure.py", line 2676, in omm_nonbonded_force
    if self.has_NBFIX():
  File "/Users/andrea/miniconda/envs/openforcefield/lib/python3.6/site-packages/parmed/amber/_amberparm.py", line 888, in has_NBFIX
    rij = comb_sig(LJ_sigma[i], LJ_sigma[j]) * fac
IndexError: list index out of range
```
Note that `AmberParm.LJRadius` is not merged correctly and it's the one causing the index error in `AmberParm.has_NBFIX` (which overrides the `Structure` implementation).

A workaround I found is to convert the `AmberParm` into pure `Structure` with
```
structure = amber_parm.copy(cls=parmed.Structure)
```
I'm not sure if this is a safe thing to do, but it seems to work for my case.

[Archive.zip](https://github.com/ParmEd/ParmEd/files/3045638/Archive.zip)

**Comment by swails** [comment]
> I'm not sure if this is a safe thing to do, but it seems to work for my case.

Yes, that's a safe thing to do.

Thanks for the report!
