### ISSUE TITLE
Amber CMAP support?

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#1066]
The new [Amber `ff19SB` forcefield](https://chemrxiv.org/articles/ff19SB_Amino-Acid_Specific_Protein_Backbone_Parameters_Trained_Against_Quantum_Mechanics_Energy_Surfaces_in_Solution/8279681/1) was recently deployed in the AmberTools 19 patch 9 release. It features CMAP terms that ParmEd does not appear to read:
```python
>>> import parmed
>>> leaprc = '/home/chodera/miniconda/envs/test/dat/leap/cmd/leaprc.protein.ff19SB'
>>> params = parmed.amber.AmberParameterSet.from_leaprc(leaprc)
Traceback (most recent call last):
  File "/home/chodera/miniconda/envs/test/lib/python3.7/site-packages/parmed/amber/parameters.py", line 688, in _process_nonbond_line
    atyp, rmin, eps = line.split()[:3]
ValueError: not enough values to unpack (expected 3, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chodera/miniconda/envs/test/lib/python3.7/site-packages/parmed/amber/parameters.py", line 295, in from_leaprc
    params.load_parameters(_find_amber_file(fname, search_oldff))
  File "/home/chodera/miniconda/envs/test/lib/python3.7/site-packages/parmed/amber/parameters.py", line 389, in load_parameters
    return self._parse_frcmod(f, line)
  File "/home/chodera/miniconda/envs/test/lib/python3.7/site-packages/parmed/amber/parameters.py", line 442, in _parse_frcmod
    self._process_nonbond_line(line)
  File "/home/chodera/miniconda/envs/test/lib/python3.7/site-packages/parmed/amber/parameters.py", line 691, in _process_nonbond_line
    '[%s]' % line)
parmed.exceptions.ParameterError: Could not understand nonbond parameter line [CMAP]
```
A copy of the parameters can be found [here](https://github.com/csimmerling/ff19SB_201907). They utilize [`set default cmap on`](https://github.com/csimmerling/ff19SB_201907/blob/master/forcefield_files/leaprc.protein.ff19SB#L83) in the leaprc file. The [CMAP terms are defined in the frcmod file](https://github.com/csimmerling/ff19SB_201907/blob/master/forcefield_files/frcmod.ff19SB#L847).

Does ParmEd need to be extended to support these terms?

**Comment by swails** [comment]
> Does ParmEd need to be extended to support these terms?

Most likely.  This should be pretty quick.

**Comment by swails** [comment]
I take it back.  The introduction of CMAPs was *not* well-conceived.  While every other term is defined between atom types, CMAPs in the frcmod file are defined for a specific residue by residue name.  No other package supported by ParmEd does this, so ParmEd has no inherent support for it.  Neither does OpenMM.

Which means ParmEd itself will have to implement an equivalent scheme.  I'm not sure why this choice was made -- my best guess is that it was to avoid having to introduce new atom types.  But this whole reinventing the wheel mindset (where no wheel is the same size or shape) makes tasks like what ParmEd is trying to do *much* harder.

**Comment by dscerutti** [comment]
I recently added CMAP support to mdgx, and this business of assigning parameters based on residue (AND ATOM--note the atom names can matter, too) was the first thing I noticed.  There are "default" atom names assigned to any CMAP--specifically C, N, CA, C, and N, to appear on the "default" relative residue numbering, specifically -1, 0, 0, 0, and +1.  This is obviously geared towards protein phi, psi  terms.

But the *true* CMAP, as explained by my go-to CHARMM expert, is supposed to be able to take any two dihedrals, not just two dihedrals that share three atoms in the form A-B-C-D and B-C-D-E.  Whether ill-conceived or not, I have a means for fitting the CMAPs in a linear least squares problem alongside all the other bonded terms, making mdgx unique among force field tools. (Tom Darden thinks that the surface fitting approach may even be novel in its own right.)

Good luck adding this to ParmEd--it will be helpful, even though tleap provides us a reasonable means in lieu of the Python suite.
