### ISSUE TITLE
unable to create CHARMM prm file from GROMACS top file

### ISSUE THREAD

**Issue by asgharrazavi** [ParmEd/ParmEd#1111]
I am trying to use Gromacs top and gro files to create charmm prm file using [this ](https://github.com/ParmEd/ParmEd/issues/305#issuecomment-293444294)post's code. However, I am getting errors. Here is the discription:

gro file:
<pre>
GROningen MAchine for Chemical Simulation
   16
    1LIG    C24    1  -0.024   0.137  -1.995
    1LIG    C26    2   0.131  -0.020  -1.894
    1LIG    C28    3   0.025   0.146  -1.756
    1LIG    C23    4  -0.043   0.194  -1.868
    1LIG    C25    5   0.066   0.030  -2.007
    1LIG    C27    6   0.111   0.037  -1.768
    1LIG    C30    7  -0.108   0.209  -2.086
    1LIG    C31    8  -0.172   0.304  -2.014
    1LIG    N32    9  -0.135   0.296  -1.881
    1LIG    H26   10   0.199  -0.103  -1.904
    1LIG    H28   11   0.011   0.194  -1.661
    1LIG    H25   12   0.085  -0.015  -2.103
    1LIG    H30   13  -0.111   0.181  -2.190
    1LIG    H31   14  -0.240   0.372  -2.062
    1LIG   HN32   15  -0.163   0.350  -1.800
    1LIG    H27   16   0.162  -0.003  -1.682
   6.00000   6.00000   6.00000
</pre>

top file:
<pre>
;
;   File lig.top  was generated
;   By user: asgharrazavi (1001)
;   On host: ARVWS01
;   At date: Wed. October  3 16:14:03 2020
;
;   This is a standalone topology file
;
;   Created by:
;   ParmEd:       00_lig_params.py, VERSION 3.2.0
;   Executable:   00_lig_params.py
;   Library dir:  /usr/local/gromacs/share/gromacs/top
;   Command line:
;     00_lig_params.py
;

[ defaults ]
; nbfunc        comb-rule       gen-pairs       fudgeLJ fudgeQQ
1               2               no              1            0.83333     

[ atomtypes ]
; name    at.num    mass    charge ptype  sigma      epsilon
C1             6  12.010780  0.00000000  A     0.33996695       0.359824
N1             7  14.006720  0.00000000  A     0.32499985        0.71128
H1             1   1.007947  0.00000000  A     0.25996425        0.06276
H2             1   1.007947  0.00000000  A     0.25105526        0.06276
H3             1   1.007947  0.00000000  A     0.10690785      0.0656888

[ moleculetype ]
; Name            nrexcl
LIG          3

[ atoms ]
;   nr       type  resnr residue  atom   cgnr    charge       mass  typeB    chargeB      massB
; residue    1 LIG rtp LIG q 0.0
    1         C1      1    LIG    C24      1 -0.09580000  12.010780   ; qtot -0.095800
    2         C1      1    LIG    C26      2 -0.15900000  12.010780   ; qtot -0.254800
    3         C1      1    LIG    C28      3 -0.14600000  12.010780   ; qtot -0.400800
    4         C1      1    LIG    C23      4 -0.04720000  12.010780   ; qtot -0.448000
    5         C1      1    LIG    C25      5 -0.08200000  12.010780   ; qtot -0.530000
    6         C1      1    LIG    C27      6 -0.11300000  12.010780   ; qtot -0.643000
    7         C1      1    LIG    C30      7 -0.18720000  12.010780   ; qtot -0.830200
    8         C1      1    LIG    C31      8 -0.10910000  12.010780   ; qtot -0.939300
    9         N1      1    LIG    N32      9 -0.19640000  14.006720   ; qtot -1.135700
   10         H1      1    LIG    H26     10 0.12800000   1.007947   ; qtot -1.007700
   11         H1      1    LIG    H28     11 0.13000000   1.007947   ; qtot -0.877700
   12         H1      1    LIG    H25     12 0.13300000   1.007947   ; qtot -0.744700
   13         H1      1    LIG    H30     13 0.15600000   1.007947   ; qtot -0.588700
   14         H2      1    LIG    H31     14 0.16300000   1.007947   ; qtot -0.425700
   15         H3      1    LIG   HN32     15 0.29770000   1.007947   ; qtot -0.128000
   16         H1      1    LIG    H27     16 0.12800000   1.007947   ; qtot 0.000000

[ bonds ]
;    ai     aj funct         c0         c1         c2         c3
      1      4     1   0.13887 294519.979152
      1      5     1   0.13887 294519.979152
      1      7     1   0.14598 237712.779582
      2      5     1   0.13887 294519.979152
      2      6     1   0.13887 294519.979152
      2     10     1   0.10851 338125.544743
      3      4     1   0.13887 294519.979152
      3      6     1   0.13887 294519.979152
      3     11     1   0.10851 338125.544743
      4      9     1   0.13872 300921.385477
      5     12     1   0.10851 338125.544743
      6     16     1   0.10851 338125.544743
      7      8     1   0.13723 358615.474554
      7     13     1   0.10851 338125.544743
      8      9     1   0.13872 300921.385477
      8     14     1   0.10851 338125.544743
      9     15     1   0.10214 417460.566740

[ pairs ]
;    ai     aj funct         c0         c1         c2         c3
      2      4     1 0.339966951 0.179912000
      3      5     1 0.339966951 0.179912000
      1      6     1 0.339966951 0.179912000
      2      7     1 0.339966951 0.179912000
      3      7     1 0.339966951 0.179912000
      3      8     1 0.339966951 0.179912000
      5      8     1 0.339966951 0.179912000
      5      9     1 0.332483402 0.252950398
      6      9     1 0.332483402 0.252950398
      1     10     1 0.299965598 0.075137464
      3     10     1 0.299965598 0.075137464
      1     11     1 0.299965598 0.075137464
      2     11     1 0.299965598 0.075137464
      9     11     1 0.292482049 0.105640822
      4     12     1 0.299965598 0.075137464
      6     12     1 0.299965598 0.075137464
      7     12     1 0.299965598 0.075137464
     10     12     1 0.259964246 0.031380000
      4     13     1 0.299965598 0.075137464
      5     13     1 0.299965598 0.075137464
      9     13     1 0.292482049 0.105640822
      1     14     1 0.295511105 0.075137464
      4     14     1 0.295511105 0.075137464
     13     14     1 0.255509752 0.031380000
      1     15     1 0.223437399 0.076870682
      3     15     1 0.223437399 0.076870682
      7     15     1 0.223437399 0.076870682
     14     15     1 0.178981552 0.032103851
      4     16     1 0.299965598 0.075137464
      5     16     1 0.299965598 0.075137464
     10     16     1 0.259964246 0.031380000
     11     16     1 0.259964246 0.031380000

[ angles ]
;    ai     aj     ak funct         c0         c1         c2         c3
      1      4      3     1   132.6611915 642.620345
      1      4      9     1   132.6611915 642.620345
      1      5      2     1   132.6611915 642.620345
      1      5     12     1   138.3188637 279.759737
      1      7      8     1   132.6611915 642.620345
      1      7     13     1   134.7190008 295.675004
      2      5     12     1   138.3188637 279.759737
      2      6      3     1   132.6611915 642.620345
      2      6     16     1   138.3188637 279.759737
      3      4      9     1   129.6186356 35.116698
      3      6     16     1   138.3188637 279.759737
      4      1      5     1   132.6611915 642.620345
      4      1      7     1   132.6611915 642.620345
      4      3      6     1   132.6611915 642.620345
      4      3     11     1   138.3188637 279.759737
      4      9      8     1   118.7733530 470.888741
      4      9     15     1   122.0060845 324.369211
      5      1      7     1   129.6186356 35.116698
      5      2      6     1   132.6611915 642.620345
      5      2     10     1   138.3188637 279.759737
      6      2     10     1   138.3188637 279.759737
      6      3     11     1   138.3188637 279.759737
      7      8      9     1   132.6611915 642.620345
      7      8     14     1   134.7190008 295.675004
      8      7     13     1   134.7190008 295.675004
      8      9     15     1   122.0060845 324.369211
      9      8     14     1   134.7190008 295.675004

[ dihedrals ]
;    ai     aj     ak     al funct         c0         c1         c2         c3         c4         c5
      4      1      3      9     1  180.0000000  1.5341333  2
      4      3      9      1     1  180.0000000  1.5341333  2
      4      9      1      3     1  180.0000000  1.5341333  2
      5      1      2     12     1  180.0000000  1.5341333  2
      5      2     12      1     1  180.0000000  1.5341333  2
      5     12      1      2     1  180.0000000  1.5341333  2
      7      1      8     13     1  180.0000000  1.5341333  2
      7      8     13      1     1  180.0000000  1.5341333  2
      7     13      1      8     1  180.0000000  1.5341333  2
      6      2      3     16     1  180.0000000  1.5341333  2
      6      3     16      2     1  180.0000000  1.5341333  2
      6     16      2      3     1  180.0000000  1.5341333  2
      1      4      5      7     1  180.0000000  1.5341333  2
      1      5      7      4     1  180.0000000  1.5341333  2
      1      7      4      5     1  180.0000000  1.5341333  2
      3      4      6     11     1  180.0000000  1.5341333  2
      3      6     11      4     1  180.0000000  1.5341333  2
      3     11      4      6     1  180.0000000  1.5341333  2
      9      4      8     15     1  180.0000000  1.3946667  2
      9      8     15      4     1  180.0000000  1.3946667  2
      9     15      4      8     1  180.0000000  1.3946667  2
      2      5      6     10     1  180.0000000  1.5341333  2
      2      6     10      5     1  180.0000000  1.5341333  2
      2     10      5      6     1  180.0000000  1.5341333  2
      8      7      9     14     1  180.0000000  1.5341333  2
      8      9     14      7     1  180.0000000  1.5341333  2
      8     14      7      9     1  180.0000000  1.5341333  2
      1      4      3      6     1  180.0000000  10.9571369  2
      1      4      3     11     1  180.0000000  10.9571369  2
      1      4      9      8     1  180.0000000  7.8828260  2
      1      4      9     15     1  180.0000000  7.8828260  2
      1      5      2      6     1  180.0000000  10.9571369  2
      1      5      2     10     1  180.0000000  10.9571369  2
      1      7      8      9     1  180.0000000  20.0529073  2
      1      7      8     14     1  180.0000000  20.0529073  2
      2      5      1      4     1  180.0000000  10.9571369  2
      2      5      1      7     1  180.0000000  10.9571369  2
      2      6      3      4     1  180.0000000  10.9571369  2
      2      6      3     11     1  180.0000000  10.9571369  2
      3      4      1      5     1  180.0000000  10.9571369  2
      3      4      1      7     1  180.0000000  10.9571369  2
      3      4      9      8     1  180.0000000  7.8828260  2
      3      4      9     15     1  180.0000000  7.8828260  2
      3      6      2      5     1  180.0000000  10.9571369  2
      3      6      2     10     1  180.0000000  10.9571369  2
      4      1      5     12     1  180.0000000  10.9571369  2
      4      1      7      8     1  180.0000000  3.8305646  2
      4      1      7     13     1  180.0000000  3.8305646  2
      4      3      6     16     1  180.0000000  10.9571369  2
      4      9      8      7     1  180.0000000  7.8828260  2
      4      9      8     14     1  180.0000000  7.8828260  2
      5      1      4      9     1  180.0000000  10.9571369  2
      5      1      7      8     1  180.0000000  3.8305646  2
      5      1      7     13     1  180.0000000  3.8305646  2
      5      2      6     16     1  180.0000000  10.9571369  2
      6      2      5     12     1  180.0000000  10.9571369  2
      6      3      4      9     1  180.0000000  10.9571369  2
      7      1      4      9     1  180.0000000  10.9571369  2
      7      1      5     12     1  180.0000000  10.9571369  2
      7      8      9     15     1  180.0000000  7.8828260  2
      9      4      3     11     1  180.0000000  10.9571369  2
      9      8      7     13     1  180.0000000  20.0529073  2
     10      2      5     12     1  180.0000000  10.9571369  2
     10      2      6     16     1  180.0000000  10.9571369  2
     11      3      6     16     1  180.0000000  10.9571369  2
     13      7      8     14     1  180.0000000  20.0529073  2
     14      8      9     15     1  180.0000000  7.8828260  2

[ system ]
; Name
Generic title

[ molecules ]
; Compound       #mols
LIG                  1
</pre>

code:
```python
import parmed as pmd

top = pmd.load_file('lig.top', xyz='lig.gro')
top.save('charmm.psf')
top.save('charmm.crd', format='charmmcrd')
pmd.charmm.CharmmParameterSet.from_structure(top).write(top='charmm.rtf', par='charmm.prm')
```

output:
<pre>
Traceback (most recent call last):
  File "__get_prm.py", line 6, in <module>
    pmd.charmm.CharmmParameterSet.from_structure(top).write(top='charmm.rtf', par='charmm.prm')
  File "/home/asgharrazavi/miniconda3/lib/python3.7/site-packages/parmed/charmm/parameters.py", line 272, in from_structure
    ParameterSet.from_structure(struct, allow_unequal_duplicates=False)
  File "/home/asgharrazavi/miniconda3/lib/python3.7/site-packages/parmed/parameters.py", line 228, in from_structure
    raise ParameterError('Unequal bond types defined between %s and %s' % key)
parmed.exceptions.ParameterError: Unequal bond types defined between C1 and C1
</pre>

**Comment by swails** [comment]
That's because the GROMACS topology cannot be translated directly to CHARMM format.  In your GROMACS file, each bond term is specified independently.  In CHARMM, however, parameters are defined between different atom types, which makes it impossible (by definition) to define different bond terms between two pairs of atoms that have the same sets of atom types.

In your GROMACS file, you have at least two bonds between pairs of C1 atoms that have different bond lengths and/or force constants.  CHARMM doesn't support this, and so you see this exception.  You will need to either make all atom types unique here or make the parameters between equivalent types the same.

**Comment by asgharrazavi** [comment]
Very informative, thank you!
