### ISSUE TITLE
Support modified scee/scnb in OpenMM export

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#1136]
It would be useful if we could add the ability to export OpenMM systems with modified `scee` and `scnb` nonbonded scaling parameters. Attempting to convert the AMBER GLYCAM06j-1 glycan force field yields the following error:
```
Traceback (most recent call last):
  File "convert_amber.py", line 1277, in <module>
    main()
  File "convert_amber.py", line 107, in main
    convert_yaml(args.input, ffxml_dir='ffxml/')
  File "convert_amber.py", line 420, in convert_yaml
    ffxml_name = convert_leaprc(files, ffxml_dir=ffxml_dir, ignore=ignore,
  File "convert_amber.py", line 212, in convert_leaprc
    params.write(ffxml_name, provenance=provenance, write_unused=write_unused, improper_dihedrals_ordering='amber')
  File "/Users/choderaj/miniconda/envs/openmmforcefields/lib/python3.8/site-packages/parmed/openmm/parameters.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/Users/choderaj/miniconda/envs/openmmforcefields/lib/python3.8/site-packages/parmed/openmm/parameters.py", line 368, in write
    self._write_omm_nonbonded(root, skip_types, separate_ljforce)
  File "/Users/choderaj/miniconda/envs/openmmforcefields/lib/python3.8/site-packages/parmed/openmm/parameters.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/Users/choderaj/miniconda/envs/openmmforcefields/lib/python3.8/site-packages/parmed/openmm/parameters.py", line 886, in _write_omm_nonbonded
    raise NotImplementedError('Cannot currently handle mixed 1-4 '
NotImplementedError: Cannot currently handle mixed 1-4 scaling: Elec. Scaling factors 1.0, 1.2 detected
```
cc @peastman @ivy-zhang @glass-w

**Comment by swails** [comment]
My understanding is that this needs support from OpenMM.  If that support is already there, then the OpenMMParameterSet writer needs to be tweaked to write it.

**Comment by peastman** [comment]
When a ForceField creates a NonbondedForce, it calls `createExceptionsFromBonds()` on it, passing in the specified scale factors.  There's no way to use different scale factors for different molecules in the system.  To do that, we would need to build the exceptions directly.

**Comment by jchodera** [comment]
> When a ForceField creates a NonbondedForce, it calls createExceptionsFromBonds() on it, passing in the specified scale factors. There's no way to use different scale factors for different molecules in the system. To do that, we would need to build the exceptions directly.

Check out the documentation for GLYCAM in the [Amber20 manual](https://ambermd.org/doc12/Amber20.pdf). GLYCAM apparently requires different 1-4 exception scaling terms.

**Comment by jchodera** [comment]
Here's the relevant section from the [Amber20 manual](https://ambermd.org/doc12/Amber20.pdf):
![image](https://user-images.githubusercontent.com/3656088/105904936-ade46a80-5fd6-11eb-9801-930bd4a1ec54.png)

**Comment by jchodera** [comment]
@swails Do you happen to know how this mixed scaling works? I can't seem to find a description of the behavior. What should the correct behavior be?

**Comment by swails** [comment]
1-4 interactions between GLYCAM atom types have unscaled nonbonded interactions (or scaling factors of 1.0).  1-4 interactions between other atom types have the parm94 scaling factors (1.2 electrostatic and 2.0 van der Waals).

In Amber, these scaling factors are stored in the torsion arrays, as they are also used as the exception list.

Note that the `createSystem` method inside ParmEd as well as both assign exceptions manually -- that is, they add exclusions each atom pair separated by some specified number of bonds, then go through and override exclusions for each exception atom pair.  It pulls the SCEE and SCNB values from the torsion arrays to implement this "mixed scaling".

As @peastman pointed out, ForceField.createSystem uses a call that enforces a single set of scaling factors which is incompatible with more than one scaling factor.

IIRC, `ForceField` has the ability to define some post-processing code that may be able to implement the desired behavior, but my OpenMM-fu in that arena is very rusty.

**Comment by peastman** [comment]
That would probably be the most straightforward way of doing it, although it's a bit of a hack.

**Comment by jchodera** [comment]
Thanks, @swails !

@peastman : There's a lot of interest in getting the GLYCAM force field converted since glycans are critical to coronavirus spike protein interactions. If there's a way for you to tackle this within ParmEd, I have tests and conversion scripts ready in http://github.com/openmm/openmmforcefields.

**Comment by peastman** [comment]
I can provide the script that should be embedded in the force field.  How can we identify which atoms are GLYCAM types?  Do they all have a standard prefix like `glycam-`?

**Comment by jchodera** [comment]
> I can provide the script that should be embedded in the force field. How can we identify which atoms are GLYCAM types? Do they all have a standard prefix like glycam-?

We could do that! That's probably easiest.

We rely on ParmEd to export these parameter sets, though. Wouldn't it make more sense to export the script from there, and have the script just build a list of atom types defined in the export to apply nonstandard scee/scnb to?

**Comment by peastman** [comment]
I believe this script should do what you want.

```python
 <Script>
import simtk.openmm as mm
glycam_types = set(type for type in self._atomTypes if type.startswith('protein-'))
glycam_atoms = set(atom.index for atom in data.atoms if data.atomType[atom] in glycam_types)
for force in sys.getForces():
  if isinstance(force, mm.NonbondedForce):
    atom_charges = {}
    for atom in glycam_atoms:
      charge, sigma, epsilon = force.getParticleParameters(atom)
      atom_charges[atom] = charge
    for i in range(force.getNumExceptions()):
      p1, p2, chargeProd, sigma, epsilon = force.getExceptionParameters(i)
      if p1 in glycam_atoms and p2 in glycam_atoms and chargeProd._value != 0:
        force.setExceptionParameters(i, p1, p2, atom_charges[p1]*atom_charges[p2], sigma, epsilon)
 </Script>
```

I have it generating `glycam_types` based on the type names, but if you want to embed a list of types that's fine too.  It updates any exception where *both* atoms are GLYCAM types, and where the charge product is not currently 0 (which would indicate a 1-2 or 1-3 interaction).

**Comment by jchodera** [comment]
@peastman : Thanks for drafting this! I've got my hands full here---would you be able to generalize this to handle any atom types that use alternate `scee/scnb` values by atom type name, and integrate this into the OpenMM parameter [`write`](https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/parameters.py#L305) method in a PR into ParmEd? I'll then be able to use it in `openmmforcefields` to export.

The `scee/scnb` handling is already partially implemented [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/parameters.py#L964-L992). We'd just need to modify this to add this script to modify the appropriate exceptions if there are deviations from the standard assumed OpenMM scee/scnb values.

**Comment by swails** [comment]
I'm doing a pretty major cleanup of ParmEd right now. I'll be done hopefully in the next couple days, but it would help to hold off on changes until I'm done.

**Comment by jchodera** [comment]
@swails : Thanks for the heads up! If you want to take a stab at integrating this instead, that would also be awesome!

We're hoping we can get glycan support into `openmmforcefields` quickly so we can stand up our pipeline for monitoring SARS-CoV-2 spike protein escape mutations for our collaborators working on antibody therapeutics.

**Comment by jchodera** [comment]
@swails: Was the cleanup in https://github.com/ParmEd/ParmEd/pull/1138 the one you wanted us to wait for? Are we able to proceed with modifying the OpenMM export to handle `scee/scnb`?

**Comment by swails** [comment]
Yes!  Good to go now.

**Comment by peastman** [comment]
Can you give more details on exactly what you want me to implement?  How will ParmEd know whether it needs to include this script?  How are the type names identified?

**Comment by jchodera** [comment]
@peastman : Here's what I'm thinking: Currently, writing nonbonded parameters for OpenMM [simply raises an issue if some exceptions should have non-default 1-4 terms](https://github.com/ParmEd/ParmEd/blob/917343a9f4afc89965d0642ae10eb7550427e508/parmed/openmm/parameters.py#L935-L955). But all this information is there---it's just not being used. 

Instead, you could keep track of those specific atom type names that have non-default 1-4 interactions, and append to the XML file a script that modifies the 1-4 interactions based on that list of atom type name pairs. This is similar to what you were thinking based on hard-coded prefixes, but would be automated to be specific to the type names that have non-default 1-4 parameters.

That way, this would work generally for any parameter sets with non-default 1-4 interactions.

Does that make sense?

So sorry for not being able to do this myself---I am buried in other things, but could tackle the conversion of glycan parameters and a new release for `openmmforcefields` after this is integrated.

**Comment by peastman** [comment]
Can you provide inputs for a case that encounters this situation?  I'll see if I can get it working.

**Comment by jchodera** [comment]
@peastman : If you install `ambertools` from `conda-forge` and grab the [`openmmforcefields` repo](https://github.com/openmm/openmmforcefields/tree/master/amber), you can run
```python
python convert_amber.py --input glycan.yaml --verbose
```
to run the conversion for [`glycan.yaml`](https://github.com/openmm/openmmforcefields/blob/master/amber/glycan.yaml) through ParmEd. This attempts to convert the `leaprc.GLYCAM_06j-1` file, which contains non-default `scee/scnb` in the files it loads.

**Comment by peastman** [comment]
How general do we need this to be?  The scaling factors in ParmEd are associated with torsions, which means in principle every torsion (defined by a sequence of four atom types) could have a different set of scale factors.  Which of the following simplifying assumptions are alright to make?

- The scaling factors will only depend on the types of the two interacting atoms, not the other two atoms connecting them.
- The scaling factors will only depend on the types of individual atoms.  If an atom type uses particular scaling factors for one 1-4 interaction, it will use those same factors for *every* 1-4 interaction.
- We don't need to support more than two sets of scaling factors.
- One of those sets will have scaling factors of 1.0, so for any individual 1-4 interaction, the only question is whether it's scaled or unscaled.

**Comment by swails** [comment]
All four of those assumptions are correct. I don't see that the last one (assuming one scaling factor is 1.0) makes the code any simpler even in principle.

**Comment by peastman** [comment]
> Instead, you could keep track of those specific atom type names that have non-default 1-4 interactions, and append to the XML file a script that modifies the 1-4 interactions based on that list of atom type name pairs.

That doesn't work with the way your conversion script is currently written.  It first runs ParmEd to generate the XML file as usual.  Then it modifies the XML file to insert a prefix in front of the atom type in attributes like `name="..."` or `type="..."`.  It doesn't know how to change the names inside the script, and ParmEd doesn't know that you're going to be changing the names later.  The script comes out looking like

```python
unscaled_types = ["NT", "H2", "Ho", "Cj", "Cy", "NH", "Cg", "C", "H1", "Os", "N", "Oy",
    "Hp", "Cp", "CX", "Hc", "3C", "CT", "Ng", "N3", "Ha", "P", "2C", "Sm",
    "Ck", "H", "O", "S", "Oh", "O2"]
```

when in fact the types should be `["glycan-NT", "glycan-H2", ...]`.  The simplest solution would be to just modify your script to look for this particular case.  It's a little hacky, but it would work.

**Comment by jchodera** [comment]
What if we added an option to the parmed OpenMM write method to accept an optional prefix that could be used consistently? I'd like to move any of this special logic into ParmEd if at all possible.

**Comment by peastman** [comment]
> I don't see that the last one (assuming one scaling factor is 1.0) makes the code any simpler even in principle.

Possibly it doesn't, but I don't understand the logic well enough to be convinced it doesn't.  Here's the code it uses to check the scaling factors.

https://github.com/ParmEd/ParmEd/blob/96cac39e418ec5de303803fd3a0009d6293d3ca1/parmed/openmm/parameters.py#L942-L953

The ifs imply that any dihedral type can leave either or both scale factors undefined.  In that case, it uses the values from a different dihedral type, as long as only one is defined.  One type might specify scee=1.5, scnb=undefined, while another one specifies scee=undefined, scnb=2.0, and it combines them to figure out scee=1.5, scnb=2.0.  How does this extend to larger numbers of types?  You could get interesting combinations of types with different combinations of defined and undefined values, and I'm not sure how to handle that.  Treating scee=1, scnb=1 as a special case and keeping the rest of the logic unchanged avoids that.
