### ISSUE TITLE
Unattached water virtual sites

### ISSUE THREAD

**Issue by rosemary-cresset** [ParmEd/ParmEd#1216]
Hi, 

I have a workflow where I create a system with OpenMM, then load the topology into ParmEd and write out prmtop and inpcrd files. I then load the files into OpenMM again using openmm.app.AmberPrmtopFile() and openmm.app.AmberInpcrdFile() and call createSystem from OpenMM, at which point I can add constraints etc. However, I am finding that when I do this with 4-point water models, then the dummy atoms don't seem to be attached to the waters and running dynamics fails. By trial and error, I discovered that if I call omm_set_virtual_sites before writing the prmtop then my problem is solved, but I am bit a puzzled by this as a solution. Is it a bug that the sites are not attached when they are read from OpenMM into ParmEd? Also, is my workflow something you would recommend or do you think I would be safer reading the files back in again using ParmEd and creating my OpenMM system from there? 

Thank you, 

Rosie

**Comment by rosemary-cresset** [comment]
Actually, I have just realised that the solution I had thought I found does not work, I think had selected tip3p by mistake when I was testing it. Sorry for the misleading message! In that case, this is a bug report. Do you know why my dummy atoms would not be attached to the waters? Thanks.

**Comment by rosemary-cresset** [comment]
I also have problems with converting an OpenMM system with tip4pew waters into a ParmEd structure and then back into an OpenMM system. See the below example: 

```
import openmm
import openmm.app as app
import openmm.unit as units
import parmed

pdb_file = app.PDBFile('1OIT_prep.pdb')
force_field = app.ForceField('amber/protein.ff14SB.xml', 'amber/tip4pew_standard.xml')
modeller = app.Modeller(pdb_file.topology, pdb_file.positions)
modeller.addSolvent(force_field, model='tip4pew', padding=1*units.nanometers, neutralize=True)

system = force_field.createSystem(modeller.topology, rigidWater=False, nonbondedMethod=app.PME)

# Read system into ParmEd and recreate OpenMM system - does not work
#parmed_struct = parmed.openmm.load_topology(modeller.topology, system, modeller.positions)
#system = parmed_struct.createSystem(nonbondedMethod=app.PME)


integrator = openmm.LangevinMiddleIntegrator(298*units.kelvin, 1/units.picosecond, 4*units.femtoseconds)
simulation = app.Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)
simulation.minimizeEnergy()
simulation.step(100)
```

This script works fine as it is, but if the commented out lines are uncommented I get the error:
```
Traceback (most recent call last):
  File "/tmp/FieldEngine-rosemary/OpenMM_Force_Fields_3465_1/example.py", line 15, in <module>
    system = parmed_struct.createSystem(nonbondedMethod=app.PME)
  File "/home/rosemary/.conan/data/Flare-Python/8.15/cresset/stable/package/df1fa62c2254431e0db646816bf210479f59d178/lib/python3.9/site-packages/parmed/utils/decorators.py", line 18, in new_fcn
    return fcn(*args, **kwargs)
  File "/home/rosemary/.conan/data/Flare-Python/8.15/cresset/stable/package/df1fa62c2254431e0db646816bf210479f59d178/lib/python3.9/site-packages/parmed/structure.py", line 2069, in createSystem
    self.omm_set_virtual_sites(system)
  File "/home/rosemary/.conan/data/Flare-Python/8.15/cresset/stable/package/df1fa62c2254431e0db646816bf210479f59d178/lib/python3.9/site-packages/parmed/utils/decorators.py", line 18, in new_fcn
    return fcn(*args, **kwargs)
  File "/home/rosemary/.conan/data/Flare-Python/8.15/cresset/stable/package/df1fa62c2254431e0db646816bf210479f59d178/lib/python3.9/site-packages/parmed/structure.py", line 2179, in omm_set_virtual_sites
    typ = atom.frame_type
  File "/home/rosemary/.conan/data/Flare-Python/8.15/cresset/stable/package/df1fa62c2254431e0db646816bf210479f59d178/lib/python3.9/site-packages/parmed/topologyobjects.py", line 1088, in frame_type
    if len(self.parent.bonds) == 2:
AttributeError: 'NoneType' object has no attribute 'bonds'
```
I would be grateful for your thoughts on this. Thank you. 

[1OIT_prep.pdb.gz](https://github.com/ParmEd/ParmEd/files/7899526/1OIT_prep.pdb.gz)

**Comment by swails** [comment]
Every program deals with virtual sites in different ways.  Amber specifies explicit bonds between a virtual site and its parent atom while OpenMM does not.  Because Amber was my primary point of experience when writing ParmEd, I specified things the Amber way.

What would need to happen is for an explicit bond to be created between the virtual site and the parent water oxygen atom which seems not to be happening in this case.  I will try to find some time to look deeper.

**Comment by rosemary-cresset** [comment]
Thanks very much for your reply. I figure that if the virtual site positions are correct, it should be possible to add the missing bonds, so I have had a go at hacking in a solution for my own purposes in topsystem.py. Ignoring various non-ideal aspects of the code, do you think the below solution is valid for water models? It certainly doesn't crash in the dynamics stage any more and the prmtop looks sensible apart from the untidiness of each water having its own bond parameters with slightly different values at the last couple of decimal places, whereas in AMBER I think they would all share the same parameters. Hopefully there is nothing I've overlooked. 

```
if a.element is None:
    # To write an AMBER prmtop file, bonds must be present between the O atoms and the massless extra points and between the two H atoms for each water
    import math
    n_atoms = len(list(r.atoms()))
    if r.name in ['WAT', 'HOH', 'TP4', 'TP5', 'T4E'] and (n_atoms == 4 or n_atoms == 5): # OpenMM waters are called HOH, but include other possibilities just in case
        if xyz is None: # We need coordinates to calculate the correct bond lengths
            raise RuntimeError('Failed to convert OpenMM water virtual sites to AMBER format - no coordinates provided')
        # Note that virtual sites MUST have been added by addExtraParticles (don't use deprecated function convertWater) for these coordinates to be correct
        if isinstance(xyz, str):
            xyz = load_file(xyz, skip_bonds=True)
            coordinates = xyz.coordinates
        else:
            coordinates = xyz

        o_atoms = []
        h_atoms = []
        for water_atom in r.atoms():
            element = water_atom.element
            if element and element.atomic_number == 8:
                o_atoms.append(water_atom)
            elif element and element.atomic_number == 1:
                h_atoms.append(water_atom)

        if len(o_atoms) == 1 and len(h_atoms) == 2: # Definitely a water
            existing_forces = [system.getForce(i) for i in range(system.getNumForces())] # List is probably less than 10 items in size
            existing_bond_forces = [f for f in existing_forces if type(f) == mm.HarmonicBondForce]
            if len(existing_bond_forces) == 0: # Shouldn't happen as we have O-H bonds in water molecules
                bond_force = mm.HarmonicBondForce()
                system.addForce(bond_force)
            else:
                bond_force = existing_bond_forces[0]

            bond_force_constant_kj_mol_nm2 = 462750.4 # k for OW-EP and HW-HW - original value from dat/leap/parm/frcmod.tip4p* and converted value from openmmff xml files

            # Add OW-EP bond
            oxygen_pos = coordinates[o_atoms[0].index]
            extra_point_pos = coordinates[a.index]
            o_ex_distance_nm = math.sqrt((oxygen_pos.x - extra_point_pos.x)**2 + (oxygen_pos.y - extra_point_pos.y)**2 + (oxygen_pos.z - extra_point_pos.z)**2)
            bond_force.addBond(o_atoms[0].index, a.index, o_ex_distance_nm, bond_force_constant_kj_mol_nm2)

            # Add HW-HW bond
            h1_pos = coordinates[h_atoms[0].index]
            h2_pos = coordinates[h_atoms[1].index]
            h_h_distance_nm = math.sqrt((h1_pos.x - h2_pos.x)**2 + (h1_pos.y - h2_pos.y)**2 + (h1_pos.z - h2_pos.z)**2)
            bond_force.addBond(h_atoms[0].index, h_atoms[1].index, h_h_distance_nm, bond_force_constant_kj_mol_nm2)

            a.name = 'EP' # Must be called EP or LP for the virtual sites to be recognised by OpenMM or AMBER when reading the prmtop file
    atom = ExtraPoint(name=a.name)
```
