### ISSUE TITLE
energy_decomposition from openmm run

### ISSUE THREAD

**Issue by spadavec** [ParmEd/ParmEd#1307]
Hello--

I have an openmm trajectory that I'd like to run `parmed.openmm.energy_decomposition` on. All of the documentation appears to require that you run with Amber files--is that correct? Are there any examples of running this function with just a trajectory and pdb/top file? 

edit: 

I'm now trying to generate prmtop and rst7 files on the fly and run things that way:

```python

    pdbfile = PDBFile('output/Jnk1_apo_minimised.pdb')
    s = parmed.openmm.topsystem.load_topology(
        pdbfile.topology, system, pdbfile.positions)
    s.save('test.prmtop', overwrite=True)
```
where `System` was defined earlier in my openmm script in the normal fashion. However, I'm getting the following error: 

```
Traceback (most recent call last):
  File "run_openmm_series.py", line 170, in <module>
    run_apo_structure(structure_name)
  File "run_openmm_series.py", line 126, in run_apo_structure
    s.save('test.prmtop', overwrite=True)
  File "/home/spadavec/miniconda3/envs/EDC/lib/python3.8/site-packages/parmed/structure.py", line 1507, in save
    s = amber.AmberParm.from_structure(self)
  File "/home/spadavec/miniconda3/envs/EDC/lib/python3.8/site-packages/parmed/amber/_amberparm.py", line 349, in from_structure
    inst.remake_parm()
  File "/home/spadavec/miniconda3/envs/EDC/lib/python3.8/site-packages/parmed/amber/_amberparm.py", line 676, in remake_parm
    self._xfer_bond_info()
  File "/home/spadavec/miniconda3/envs/EDC/lib/python3.8/site-packages/parmed/amber/_amberparm.py", line 1580, in _xfer_bond_info
    bond.type.used = True
AttributeError: 'NoneType' object has no attribute 'used'
```

**Comment by spadavec** [comment]
Just realized this sub-issue was solved in #1248. Closing.

**Comment by spadavec** [comment]
Sorry, it turns out I haven't completely solved this yet. I'm trying the following: 

```python 
def run_apo_structure(structure_name):
    temperature = 300 * unit.kelvin
    equilibration_steps = 5500
    reporting_interval = 100

    input_pdb = f'input/Inputs_for_FEP/{structure_name}_fixed_protein.pdb'

    pdb_in = input_pdb

    output_traj_h5 = f'./output/{structure_name}_apo_traj.nc'
    output_min = f'./output/{structure_name}_apo_minimised.pdb'

    num_steps = 17500

    # check whether we have a GPU platform and if so set the precision to mixed
    speed = 0

    for i in range(Platform.getNumPlatforms()):
        p = Platform.getPlatform(i)
        if p.getSpeed() > speed:
            platform = p
            speed = p.getSpeed()

    if platform.getName() == 'CUDA' or platform.getName() == 'OpenCL':
        platform.setPropertyDefaultValue('Precision', 'mixed')
        print('Set precision for platform', platform.getName(), 'to mixed')

    # Initialize a SystemGenerator using the GAFF for the ligand and tip3p for the water.
    forcefield_kwargs = {'constraints': app.HBonds, 'rigidWater': True,
                         'removeCMMotion': True, 'hydrogenMass': 4 * unit.amu, 'flexibleConstraints': True}
    system_generator = SystemGenerator(
        forcefields=['amber/ff14SB.xml', 'amber/tip3p_standard.xml'],
        small_molecule_forcefield='gaff-2.11',
        molecules=[],
        forcefield_kwargs=forcefield_kwargs)

    protein_pdb = PDBFile(pdb_in)
    modeller = Modeller(protein_pdb.topology, protein_pdb.positions)
    modeller.addSolvent(system_generator.forcefield,
                        model='tip3p', padding=6.0 * unit.angstroms)

    # Create the system using the SystemGenerator
    system = system_generator.create_system(modeller.topology)

    integrator = LangevinIntegrator(
        temperature, 1 / unit.picosecond, 0.004 * unit.picoseconds)
    system.addForce(openmm.MonteCarloBarostat(
        1 * unit.atmospheres, temperature, 25))

    simulation = Simulation(modeller.topology, system,
                            integrator, platform=platform)
    context = simulation.context
    context.setPositions(modeller.positions)

    simulation.minimizeEnergy()

    # Write out the minimised PDB. The 'enforcePeriodicBox=False' bit is important otherwise the different
    # components can end up in different periodic boxes resulting in really strange looking output.
    with open(output_min, 'w+') as outfile:
        PDBFile.writeFile(modeller.topology, context.getState(
            getPositions=True, enforcePeriodicBox=False).getPositions(), file=outfile, keepIds=False)

    simulation.context.setVelocitiesToTemperature(temperature)
    simulation.step(equilibration_steps)

    simulation.reporters.append(NetCDFReporter(
        output_traj_h5, reporting_interval))
    simulation.reporters.append(StateDataReporter(
        sys.stdout, reporting_interval * 5, step=True, potentialEnergy=True, temperature=False))

    simulation.step(num_steps)
    import mdtraj
    pdbfile = PDBFile('output/Jnk1_apo_minimised.pdb')
    traj = mdtraj.load('output/Jnk1_apo_traj.h5')
    xyz = traj.xyz
    s = parmed.openmm.topsystem.load_topology(
        pdbfile.topology, system, xyz)

    s.save('test.prmtop', overwrite=True)
    s.save('test.rst7', overwrite=True, format='rst7')

    parm = parmed.load_file('test.prmtop', 'test.rst7')
    parm_system = parm.createSystem()
    print(parmed.openmm.energy_decomposition_system(parm, system))
```

The energies I'm getting are, well, silly: 

```
[('HarmonicBondForce', 15887634.26065536), ('PeriodicTorsionForce', 4967.9837334673975), ('NonbondedForce', 7.954311798700266e+16), ('CMMotionRemover', 0.0), ('HarmonicAngleForce', 3464.385919859828), ('MonteCarloBarostat', 0.0)]
```

I'm clearly doing something very wrong--can someone point me in the right direction?

**Comment by swails** [comment]
I *think* that the problem is here:

```python
    import mdtraj
    pdbfile = PDBFile('output/Jnk1_apo_minimised.pdb')
    traj = mdtraj.load('output/Jnk1_apo_traj.h5')
    xyz = traj.xyz
    s = parmed.openmm.topsystem.load_topology(
        pdbfile.topology, system, xyz)
```

I believe that mdtraj operates in the same internal units as OpenMM (kJ, nm, dalton [I think] and ps) while ParmEd operates in the AKMA unit system (Angstrom, kcal, dalton [I think], and the time unit needed to make these consistent).  When units are attached, ParmEd will do the internal conversion to its internal unit system.  When units are not attached, it really has no choice but to assume they're in the proper units already.

In this case, I believe that the `xyz = traj.xyz` is a unitless numpy array in nanometers.  In the ParmEd structure, this array is treated as being in Angstroms.

I think you can fix this by changing `xyz = traj.xyz` to `xyz = traj.xyz / 10`.
