### ISSUE TITLE
python 3.8 incompatibility from functools.cache issue

### ISSUE THREAD

**Issue by mmfarrugia** [ParmEd/ParmEd#1318]
Hello,

I am working with a large set of code and the Schrodinger 2021u4 python interpreter so I cannot include all of the files for reproducibility (I do not have the Schrodinger modules, hence the interpreter use and the package compatibility issues), my apologies.

I've pinpointed the issue, but not a viable solution and hope to both point out a version compatibiltity issue which would require python>=3.9 restriction over python>=3.8 as well as ask for your suggestions regarding a solution.

Schrodinger 2021.u4 is based on python 3.8.  **parmed currently only requires 3.8+ but it uses functools.cache in modeller/standardtemplates.py**, thus according to [my searching](https://stackoverflow.com/questions/66846743/importerror-cannot-import-name-cache-from-functools) **parmed is incompatible with python 3.8 because functools.cache is only available from python3.9+.**  

**If I would like to resolve this issue, what version of parmed could I revert to?**  

Additionally, I am having to create an egg in order for the Schrodinger interpreter to play nice with any other modules I need to use in my code (github repo Q2MM/q2mm seminario branch in the seminario.py script).  Thus, I cannot just use the conda package, I have to clone down the github, modify setup.py, and then build my egg so if you could include a commit or github repo ssh address for download of the last python3.8 compatible version of parmed I would be very grateful.

For error context:
`$SCHRODINGER/run ../../../q2mm/seminario.py -i theo-tsnadhm06.frcmod -o out.frcmod -m theo-tsnadhm06.mol2 -gl theo-tsnadhm06.log`
^ The command to run the seminario script once schrodinger module is loaded.

`Traceback (most recent call last):
  File "./../../../q2mm/seminario.py", line 19, in <module>
    import parmed
  File "<frozen zipimport>", line 259, in load_module
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+4.g7ba559fc.dirty-py3.8-linux-x86_64.egg/parmed/__init__.py", line 24, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+4.g7ba559fc.dirty-py3.8-linux-x86_64.egg/parmed/amber/__init__.py", line 11, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+4.g7ba559fc.dirty-py3.8-linux-x86_64.egg/parmed/amber/amberformat.py", line 13, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+4.g7ba559fc.dirty-py3.8-linux-x86_64.egg/parmed/formats/__init__.py", line 9, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+4.g7ba559fc.dirty-py3.8-linux-x86_64.egg/parmed/formats/mol2.py", line 10, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+4.g7ba559fc.dirty-py3.8-linux-x86_64.egg/parmed/modeller/__init__.py", line 11, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+4.g7ba559fc.dirty-py3.8-linux-x86_64.egg/parmed/modeller/standardtemplates.py", line 6, in <module>
ImportError: cannot import name 'cache' from 'functools' (/opt/crc/s/schrodinger/2021u4/internal/lib/python3.8/functools.py)
`

Again, my apologies for the lack of files and code included, I hope I have included enough so that someone with Schrodinger license and access to github (my repo is public) can reproduce, but I tried to pinpoint the problem and explain it such that it doesn't require much debug work.

Thank you!

Mikaela

UPDATE:
Wanted to include results of my git blame:
7ba559fce (Jason Swails 2023-09-12 10:04:46 -0400   6) from functools import cache

**Comment by mmfarrugia** [comment]
UPDATE:

A separate issue arises from using either the commit associated with the changeset prior to the one which uses functools.cache as well as using the commit changeset associated with v4.1.0 release:

`(tsff) [mfarrugi@crcfe01 hp-thiohemiacet]$ $SCHRODINGER/run ../../../q2mm/seminario.py -i theo-tsnadhm06.frcmod -o out.frcmod -m theo-tsnadhm06.mol2 -gl theo-tsnadhm06.log` 


```
Traceback (most recent call last):
  File "./../../../q2mm/seminario.py", line 19, in <module>
    import parmed
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+3.gbf0790f8.dirty-py3.8-linux-x86_64.egg/parmed/__init__.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+3.gbf0790f8.dirty-py3.8-linux-x86_64.egg/parmed/amber/__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+3.gbf0790f8.dirty-py3.8-linux-x86_64.egg/parmed/amber/amberformat.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+3.gbf0790f8.dirty-py3.8-linux-x86_64.egg/parmed/formats/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+3.gbf0790f8.dirty-py3.8-linux-x86_64.egg/parmed/formats/mol2.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+3.gbf0790f8.dirty-py3.8-linux-x86_64.egg/parmed/modeller/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+3.gbf0790f8.dirty-py3.8-linux-x86_64.egg/parmed/modeller/standardtemplates.py", line 19, in <module>
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+3.gbf0790f8.dirty-py3.8-linux-x86_64.egg/parmed/amber/offlib.py", line 108, in parse
  File "/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+3.gbf0790f8.dirty-py3.8-linux-x86_64.egg/parmed/utils/io.py", line 95, in genopen
    from _io import _WindowsConsoleIO
NotADirectoryError: [Errno 20] Not a directory: '/afs/crc.nd.edu/user/m/mfarrugi/tools-repo/ParmEd/dist/ParmEd-4.1.0+3.gbf0790f8.dirty-py3.8-linux-x86_64.egg/parmed/modeller/data/standard_residues.lib'
```
I may be off-base, but I don't believe this is related to my conda environment and I notice that the commit associated with the py3.8 incompatibility is only 24 hours old so I will stop trying to debug now.  If you do end up needing further details on my environment to troubleshoot this then please let me know.

**Comment by swails** [comment]
Very true, `functools.cache` was added in Python 3.9.  I added a compatibility shim that I can keep there until Python 3.8 hits EOL and we can drop support.

Thanks for finding this and raising an issue!  It's great to get it fixed quickly.

As for the second error, it's a result of one of the data files not being properly "installed" (or findable by Python).  It's not related to a Python version issue.  Something got messed up in the installation process, and not all the files that should've made it into the distribution made it there.

**Comment by mmfarrugia** [comment]
Yes, I will test this out. Unfortunately, I may not get to it until Monday morning though, I will keep you updated. Thank you for replying so quickly!

I was eventually able to make an egg from the 4.0.0 release by the way, it seems I missed the setup.py install step and went straight to the egg building for the 4.0.0 attempt.
