### ISSUE TITLE
OpenMM to Gromacs conversion using ParmEd

### ISSUE THREAD

**Issue by sameersaurav** [ParmEd/ParmEd#1342]
I want to get gromacs topology file from OpenMM simulation. 

**My code-**

smirnoff = SMIRNOFFTemplateGenerator(forcefield='openff-2.0.0.offxml')

sdf_files = ['bcd_gly.sdf', 'aspirin.sdf']
for i in range(len(sdf_files)):
    offmol = Molecule.from_file(sdf_files[i])
    smirnoff.add_molecules(offmol)

from openmm.app import ForceField

forcefield = app.ForceField('amber14-all.xml', 'tip3p.xml', 'amber/GLYCAM_06j-1.xml')
forcefield.registerTemplateGenerator(smirnoff.generator)

pdb = parmed.load_file('Umb_16.pdb')

hg_system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.PME,nonbondedCutoff=1*unit.nanometer,removeCMMotion=False,rigidWater=False,constraints=None)

pmd_structure = parmed.openmm.load_topology(pdb.topology, system=hg_system, xyz=pdb.positions)

pmd_structure.save("SYSTEM.top", overwrite=True)
pmd_structure.save("SYSTEM.gro", overwrite=True)

**Error -**
Traceback (most recent call last):
  File "/home/sl302/USERS/SAMEER/OpenMM/TOP/HG.py", line 36, in <module>
    pmd_structure.save("SYSTEM.top", overwrite=True)
  File "/home/sl302/anaconda3/envs/openmm-sameer/lib/python3.10/site-packages/parmed/structure.py", line 1548, in save
    s = gromacs.GromacsTopologyFile.from_structure(self)
  File "/home/sl302/anaconda3/envs/openmm-sameer/lib/python3.10/site-packages/parmed/gromacs/gromacstop.py", line 249, in from_structure
    raise GromacsError('Structure has mixed 1-4 scaling which is not supported by Gromacs')
parmed.exceptions.GromacsError: Structure has mixed 1-4 scaling which is not supported by Gromacs

I have attatched the files.
[TOP.tar.gz](https://github.com/ParmEd/ParmEd/files/14636963/TOP.tar.gz)

**Comment by sameersaurav** [comment]
Thanks a lot.
