### ISSUE TITLE
problem with combining structures

### ISSUE THREAD

**Issue by JuroDobias** [ParmEd/ParmEd#1354]
Hi,
I am trying to duplicate ligand atom in amber topology. I need this to calculate free energy of restraining ligand in ABFE calculation.

I am using parmed from recent amber24 release.
Using this script:
```
import parmed as pmd

mask=':LIG'
top='system.parm7'
rst7='system.rst7'

lig = pmd.load_file(top, xyz=rst7)[mask]
outStr = pmd.load_file(top, xyz=rst7)
outStr+=lig
```
errored:
```
  File "/home2/jurajdobias/amber/cGAS/myFE/all/parmedBug/test.py", line 11, in <module>
    outStr+=lig
  File "/home2/jurajdobias/amber/amber24/lib/python3.12/site-packages/parmed/amber/_amberparm.py", line 410, in __iadd__
    super(AmberParm, self).__iadd__(other)
  File "/home2/jurajdobias/amber/amber24/lib/python3.12/site-packages/parmed/structure.py", line 3591, in __iadd__
    other = copy(other)
            ^^^^^^^^^^^
  File "/home2/jurajdobias/amber/amber24/miniconda/lib/python3.12/copy.py", line 79, in copy
    return copier(x)
           ^^^^^^^^^
  File "/home2/jurajdobias/amber/amber24/lib/python3.12/site-packages/parmed/amber/_amberparm.py", line 365, in __copy__
    other.initialize_topology()
  File "/home2/jurajdobias/amber/amber24/lib/python3.12/site-packages/parmed/amber/_amberparm.py", line 185, in initialize_topology
    self.load_structure()
  File "/home2/jurajdobias/amber/amber24/lib/python3.12/site-packages/parmed/amber/_amberparm.py", line 478, in load_structure
    self._check_section_lengths()
  File "/home2/jurajdobias/amber/amber24/lib/python3.12/site-packages/parmed/amber/_amberparm.py", line 1272, in _check_section_lengths
    check_length('LENNARD_JONES_ACOEF', ntypes*(ntypes+1)//2)
  File "/home2/jurajdobias/amber/amber24/lib/python3.12/site-packages/parmed/amber/_amberparm.py", line 1257, in check_length
    raise AmberError(f'FLAG {key} has {len(self.parm_data[key])} elements; expected {length}')
parmed.exceptions.AmberError: FLAG LENNARD_JONES_ACOEF has 105 elements; expected 45
```
It seems adding ligand atoms messes up with number of atom types (ntypes). It expects only atom types in ligand which is 9 (9*10/2=45) but gets 14 (14*15/2=105), which is weird, because combined structure should have same number of atom types and actually 105 is correct number. If I duplicate one of water molecules (mask='@55-58'), everything works fine. I parametrized ligand with openff, so each atom has unique amber atom type. I set those atom type names to sequence aa, ab, ac, ad ... zy, zz.

I attach input parm and restart files
Any help would be appreciated.

**Comment by MauriceKarrenbrock** [comment]
A fast workaround that I found is to write your lig on Gromacs style files (lig.top, lig.pdb), re-load it from those and then merge them.

It looks like the problem is in how the `__getitem__` method is written for the `AmberParm` class

https://github.com/ParmEd/ParmEd/blob/f82923ab6b5cbbb63d818930f043c9ce64c02604/parmed/amber/_amberparm.py#L374-L389

While the `outStr.pointers['NTYPES']`  and  `lig.pointers['NTYPES']` are 14 and 9 respectively, the length of `LENNARD_JONES_ACOEF`  `LENNARD_JONES_BCOEF` and `LENNARD_JONES_CCOEF` are inherited from the starting structure and never updated.
In fact even if you try to write the lig into Amber style files and re-loading it from those you'll get the same error (that is why I suggested you to write it into Gromacs style files).

I would expect those to get updated inside this method instead of being copied by hand when generating a subtructure with a mask
https://github.com/ParmEd/ParmEd/blob/f82923ab6b5cbbb63d818930f043c9ce64c02604/parmed/amber/_amberparm.py#L1479

I am not an expert in Amber topologies though as I usually use Gromacs, so there might be something I missed or misunderstood.

**Comment by mattwthompson** [comment]
This is probably the same as #1101


A marginally simpler reproduction is to call `__copy__` on something you're trying to add together:


```python
import requests

import parmed


print(f"ParmEd version: {parmed.__version__}")

repo_url = "https://raw.githubusercontent.com/MobleyLab/benchmarksets/master/input_files/"

for filename, url in {
    "system.prmtop": f"{repo_url}/BRD4/prmtop-coords/BRD4-1.prmtop",
    "system.crd": f"{repo_url}/BRD4/prmtop-coords/BRD4-1.crds",
}.items():
    r = requests.get(url)
    open(filename, "w").write(r.text)

parm = parmed.amber.AmberParm("system.prmtop", "system.crd")

for part in parm.split():
    part[0].__copy__()

"""
ParmEd version: 4.2.2
Traceback (most recent call last):
  File "/Users/mattthompson/software/openff-toolkit/repro_split_bug.py", line 16, in <module>
    part[0].__copy__()
  File "/Users/mattthompson/micromamba/envs/smirnoff-plugins-test/lib/python3.12/site-packages/parmed/amber/_amberparm.py", line 365, in __copy__
    other.initialize_topology()
  File "/Users/mattthompson/micromamba/envs/smirnoff-plugins-test/lib/python3.12/site-packages/parmed/amber/_amberparm.py", line 185, in initialize_topology
    self.load_structure()
  File "/Users/mattthompson/micromamba/envs/smirnoff-plugins-test/lib/python3.12/site-packages/parmed/amber/_amberparm.py", line 478, in load_structure
    self._check_section_lengths()
  File "/Users/mattthompson/micromamba/envs/smirnoff-plugins-test/lib/python3.12/site-packages/parmed/amber/_amberparm.py", line 1272, in _check_section_lengths
    check_length('LENNARD_JONES_ACOEF', ntypes*(ntypes+1)//2)
  File "/Users/mattthompson/micromamba/envs/smirnoff-plugins-test/lib/python3.12/site-packages/parmed/amber/_amberparm.py", line 1257, in check_length
    raise AmberError(f'FLAG {key} has {len(self.parm_data[key])} elements; expected {length}')
parmed.exceptions.AmberError: FLAG LENNARD_JONES_ACOEF has 171 elements; expected 105
"""
