### ISSUE TITLE
parmed.exceptions.FormatNotFound: Could not identify file format, for for gromacs to amber

### ISSUE THREAD

**Issue by jakobcasa** [ParmEd/ParmEd#1382]
Dear all

I have tried to convert my GROMACS  .top to the amber analog. The error which occurs is: 
Traceback (most recent call last):
  File "/projects/efv45/rgz30/jakob/joyce/Noneq@MeCN/NVT_produ_starts/Produ_NVT_2/test", line 11, in <module>
    gmx_top = pmd.load_file('./pt-complex_S0@MeCN.top', xyz='./confout.gro')
  File "/home/efv45/rgz30/amber/amber20/lib/python3.9/site-packages/parmed/formats/registry.py", line 182, in load_file
    raise FormatNotFound('Could not identify file format')
parmed.exceptions.FormatNotFound: Could not identify file format

The version of ParmEd is 3.4.1, and is in the amber program.

It is to be noted that I don't use an OPLS, and all the FF parameters are in the .top file.

Please let me know if you need more information, and I can try to post it here.

I appreciate your help!

Best
Jakob

**Comment by swails** [comment]
Can you attach your GROMACS topology file? There's a problem with the automatic type detection, so you can always try to instantiate the system using the GROMACS topology object itself instead of the `load_file` helper.

**Comment by jakobcasa** [comment]
Dear swalis
[pt-complex_S0@MeCN-1.txt](https://github.com/user-attachments/files/18129171/pt-complex_S0%40MeCN-1.txt)

I did attach the file here (in txt, because top was not supported):

[pt-complex_S0@MeCN-1.txt](https://github.com/user-attachments/files/18129171/pt-complex_S0%40MeCN-1.txt)


When I deleted the comment at the beginning of the file, it was able to check that it is top file but is was still not able to do the transformation to the Amber .prmtop correctly.

Have a nice weekend

Best Jakob
