### ISSUE TITLE
'module' object has no attribute 'Cmd'

### ISSUE THREAD

**Issue by ever4cyth** [ParmEd/ParmEd#148]
```
python test_chemistry_charmm.py 
Traceback (most recent call last):
  File "test_chemistry_charmm.py", line 4, in <module>
    from chemistry.utils.six import iteritems
  File "/home/magnolia/python/lib/python2.7/site-packages/chemistry/__init__.py", line 14, in <module>
    from chemistry import amber, charmm, tinker, openmm, rosetta
  File "/home/magnolia/python/lib/python2.7/site-packages/chemistry/amber/__init__.py", line 10, in <module>
    from chemistry.amber.amberformat import AmberFormat, FortranFormat
  File "/home/magnolia/python/lib/python2.7/site-packages/chemistry/amber/amberformat.py", line 18, in <module>
    from fortranformat import FortranRecordReader, FortranRecordWriter
  File "/home/magnolia/python/lib/python2.7/site-packages/fortranformat/__init__.py", line 37, in <module>
    exec('from FortranRecordReader import FortranRecordReader')
  File "<string>", line 1, in <module>
  File "/home/magnolia/python/lib/python2.7/site-packages/fortranformat/FortranRecordReader.py", line 9, in <module>
    exec('from _input import input as _input')
  File "<string>", line 1, in <module>
  File "/home/magnolia/python/lib/python2.7/site-packages/fortranformat/_input.py", line 2, in <module>
    import pdb
  File "/usr/lib/python2.7/pdb.py", line 59, in <module>
    class Pdb(bdb.Bdb, cmd.Cmd):
AttributeError: 'module' object has no attribute 'Cmd'
```

the python is shipped with ubuntu 12.04. Please help.

**Comment by swails** [comment]
The error is arising because the `cmd` module has no attribute `Cmd`.  But it very clearly does:

```Python
>>> import cmd
>>> cmd.Cmd
<class cmd.Cmd at 0x1004afe20>
>>> cmd.__file__
'/Users/swails/miniconda/envs/py27/lib/python2.7/cmd.pyc'
```

`cmd` is a module in the Python standard library, and it is being imported by the Python Debugger (`pdb`), another Python standard library module.  stdlib modules are typically more reliable than almost any other Python code out there.

Usually what this means is that you are masking a module.  If you are unfamiliar with this, what it means is that somewhere in your `PYTHONPATH` (or in your installed packages), there is a `cmd` module or package in the top-level namespace that conflicts with the standard library module.  As a result, `pdb` *actually* imports a different `cmd` module than it is trying to, one that does not have a `Cmd` class.

What is the output of this command:

```
python -c "import cmd; print(cmd.__file__)"
```
?  Or if you *know* where that other `cmd` module is coming from, either remove it or take it out of your PYTHONPATH (and if it is some of your Python code, rename the module to something *not* in the stdlib).

**Comment by ever4cyth** [comment]
Thanks a lot, Jason! Indeed somewhere in my PYTHONPATH there is another
cmd.py file. Everything is fine now.

**Comment by swails** [comment]
Good to hear

**Comment by hainm** [comment]
@ever4cyth  you reminded me about the error I got for the package I am coding. I have a file named decorator.py and got stuck with some `decorator.py` file in ipython.

Hai
