### ISSUE TITLE
[interactive mode] kicked

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#342]
```
> writeFrcmod('./test.frcmod')
Dumping FRCMOD file ('./test.frcmod') with parameters from RAN.parm7
Traceback (most recent call last):
  File "/home/haichit/anaconda3/bin/parmed", line 6, in <module>
    clapp()
  File "/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/scripts.py", line 194, in clapp
    parmed_commands.cmdloop()
  File "/home/haichit/anaconda3/lib/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/haichit/anaconda3/lib/python3.4/cmd.py", line 217, in onecmd
    return func(arg)
  File "<string>", line 1, in <lambda>
  File "/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/tools/parmed_cmd.py", line 152, in _normaldo
    action.execute()
  File "/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/tools/actions.py", line 326, in execute
    frcmod = open(self.frcmod_name, 'w')
FileNotFoundError: [Errno 2] No such file or directory: "('./test.frcmod')"
```

parmed -v
parmed: Version 2.0beta3

**Comment by swails** [comment]
Do you have permissions in that directory?

**Comment by hainm** [comment]
yes. It's in my home dir.

**Comment by hainm** [comment]
`pmd.writeFrcmod(p, 'test.frcmod')` is fine.

**Comment by swails** [comment]
You're using Python syntax in the ParmEd interpreter.  Get rid of the ()'s.

**Comment by hainm** [comment]
ha ha. Yes.

But still need to be fixed to not to be kicked out.
