### ISSUE TITLE
Bug in writing openmm ffxml files

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#567]
I'm running into an error with this code:
```python
    # Generate ffxml file contents for parmchk-generated frcmod output.
    leaprc = StringIO("parm = loadamberparams gaff.dat")
    import parmed
    params = parmed.amber.AmberParameterSet.from_leaprc(leaprc)
    params = parmed.openmm.OpenMMParameterSet.from_parameterset(params)
    citations = """\
Wang, J., Wang, W., Kollman P. A.; Case, D. A. "Automatic atom type and bond type perception in molecular mechanical calculations". Journal of Molecular Graphics and Modelling , 25, 2006, 247260.
Wang, J., Wolf, R. M.; Caldwell, J. W.;Kollman, P. A.; Case, D. A. "Development and testing of a general AMBER force field". Journal of Computational Chemistry, 25, 2004, 1157-1174.
"""
    ffxml = str()
    provenance=dict(OriginalFile='gaff.dat', Reference=citations)
    outfile = open('gaff.xml', 'w')
    params.write(outfile, provenance=provenance)
    outfile.close()
```
that gives
```
======================================================================
ERROR: Test writing XML parameters loaded from Amber GAFF parameter files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/choderalab/openmoltools/openmoltools.jchodera/openmoltools/tests/test_forcefield_generators.py", line 167, in testWriteXMLParametersGAFF
    params.write(outfile, provenance=provenance)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/parmed/openmm/parameters.py", line 152, in write
    self._write_omm_nonbonded(dest)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/parmed/openmm/parameters.py", line 346, in _write_omm_nonbonded
    if t.scee: scee.add(t.scee)
AttributeError: 'str' object has no attribute 'scee'
```
This occurs [here](https://github.com/ParmEd/ParmEd/blob/ommparams/parmed/openmm/parameters.py#L344-L348) in the code.

Adding a `print(dt)` there shows that the dihedral type is four strings:
```
('X', 'c', 'c', 'X')
```
I'm not sure quite how this code is supposed to work or why the tests did not catch this.

**Comment by jchodera** [comment]
Whoops.  Nevermind---my code just isn't up to date with the `ommparams` branch.
