### ISSUE TITLE
Problem with reading vsite from gromacs topology

### ISSUE THREAD

**Issue by n-salvi** [ParmEd/ParmEd#781]
Hello everyone

I keep getting the following error when using load_file to import a system built using gmx:

</code>Traceback (most recent call last):
  File "simulate_gromacs_pme.py", line 17, in <module>
    top = load_file('topol.top', xyz='solv_ions.gro')
  File "/home/nsalvi/programs/amber16/lib/python3.5/site-packages/parmed/formats/registry.py", line 214, in load_file
    return cls(filename, *args, **kwargs)
  File "/home/nsalvi/programs/amber16/lib/python3.5/site-packages/parmed/gromacs
/gromacstop.py", line 247, in __init__
    self.read(fname, defines, parametrize)
  File "/home/nsalvi/programs/amber16/lib/python3.5/site-packages/parmed/gromacs
/gromacstop.py", line 363, in read
    b, bt = self._parse_vsites3(line, molecule.atoms, params)
  File "/home/nsalvi/programs/amber16/lib/python3.5/site-packages/parmed/gromacs
/gromacstop.py", line 676, in _parse_vsites3
    a, b = float(words[5]), float(words[6])
IndexError: list index out of range</code>

That is because all the lines concerning vsites in my .top files have 5 values, for example:

</code>[ virtual_sites3 ]
;  ai    aj    ak    al funct            c0            c1            c2
    5     7     1     2    -4</code>

Could you help me with that?

Thank you in advance

Nicola

**Comment by swails** [comment]
I'm not even sure how to read that line. Why are there not 2 weights? What does the negative weight mean?
