### ISSUE TITLE
Compatibility to OpenMM system TIP3P water box

### ISSUE THREAD

**Issue by andrrizzi** [ParmEd/ParmEd#868]
OpenMM `tip3p.xml` forcefield doesn't include bond parameters. I believe this is causing `Structure.createSystem` to fail. For example, this script
```python
import parmed
from simtk import unit
from openmmtools.testsystems import WaterBox
# WaterBox uses openmm.app.Forcefield('tip3p.xml') and app.Modeller.addSolvent to create a water box.
water_box = WaterBox(box_edge=5.0*unit.angstrom, model='tip3p')
topology, system, positions = water_box.topology, water_box.system, water_box.positions
structure = parmed.openmm.topsystem.load_topology(topology, system, positions)
structure.createSystem()
```
fails with
```
Traceback (most recent call last):
  File "create_input_files.py", line 169, in <module>
    structure.createSystem()
  File "/Users/andrea/miniconda/envs/yankdev/lib/python3.5/site-packages/parmed/utils/decorators.py", line 31, in new_fcn
    return fcn(*args, **kwargs)
  File "/Users/andrea/miniconda/envs/yankdev/lib/python3.5/site-packages/parmed/structure.py", line 2050, in createSystem
    self.omm_add_constraints(system, constraints, rigidWater)
  File "/Users/andrea/miniconda/envs/yankdev/lib/python3.5/site-packages/parmed/utils/decorators.py", line 31, in new_fcn
    return fcn(*args, **kwargs)
  File "/Users/andrea/miniconda/envs/yankdev/lib/python3.5/site-packages/parmed/structure.py", line 2143, in omm_add_constraints
    bond.type.req*length_conv)
AttributeError: 'NoneType' object has no attribute 'req'
```
if I substitute the `createSystem` call with
```python
structure.createSystem(constraints=None, rigidWater=None)
```
I get
```
Traceback (most recent call last):
  File "create_input_files.py", line 169, in <module>
    structure.createSystem(constraints=None, rigidWater=None)
  File "/Users/andrea/miniconda/envs/yankdev/lib/python3.5/site-packages/parmed/utils/decorators.py", line 31, in new_fcn
    return fcn(*args, **kwargs)
  File "/Users/andrea/miniconda/envs/yankdev/lib/python3.5/site-packages/parmed/structure.py", line 2059, in createSystem
    flexibleConstraints)
  File "/Users/andrea/miniconda/envs/yankdev/lib/python3.5/site-packages/parmed/utils/decorators.py", line 31, in new_fcn
    return fcn(*args, **kwargs)
  File "/Users/andrea/miniconda/envs/yankdev/lib/python3.5/site-packages/parmed/structure.py", line 2269, in omm_bond_force
    raise ParameterError('Cannot find necessary parameters')
parmed.exceptions.ParameterError: Cannot find necessary parameters
```
The serialization of the OpenMM System is (system with two water molecules)
```
<?xml version="1.0" ?>
<System openmmVersion="7.1" type="System" version="1">
	<PeriodicBoxVectors>
		<A x=".5" y="0" z="0"/>
		<B x="0" y=".5" z="0"/>
		<C x="0" y="0" z=".5"/>
	</PeriodicBoxVectors>
	<Particles>
		<Particle mass="15.99943"/>
		<Particle mass="1.007947"/>
		<Particle mass="1.007947"/>
		<Particle mass="15.99943"/>
		<Particle mass="1.007947"/>
		<Particle mass="1.007947"/>
	</Particles>
	<Constraints>
		<Constraint d=".09572" p1="0" p2="1"/>
		<Constraint d=".09572" p1="0" p2="2"/>
		<Constraint d=".09572" p1="3" p2="4"/>
		<Constraint d=".09572" p1="3" p2="5"/>
		<Constraint d=".15139006545247014" p1="1" p2="2"/>
		<Constraint d=".15139006545247014" p1="4" p2="5"/>
	</Constraints>
	<Forces>
		<Force forceGroup="0" type="HarmonicBondForce" usesPeriodic="0" version="2">
			<Bonds/>
		</Force>
		<Force forceGroup="0" type="HarmonicAngleForce" usesPeriodic="0" version="2">
			<Angles/>
		</Force>
		<Force alpha="0" cutoff=".9" dispersionCorrection="1" ewaldTolerance=".0005" forceGroup="0" method="4" nx="0" ny="0" nz="0" recipForceGroup="-1" rfDielectric="78.3" switchingDistance=".75" type="NonbondedForce" useSwitchingFunction="1" version="1">
			<Particles>
				<Particle eps=".635968" q="-.834" sig=".3150752406575124"/>
				<Particle eps="0" q=".417" sig="1"/>
				<Particle eps="0" q=".417" sig="1"/>
				<Particle eps=".635968" q="-.834" sig=".3150752406575124"/>
				<Particle eps="0" q=".417" sig="1"/>
				<Particle eps="0" q=".417" sig="1"/>
			</Particles>
			<Exceptions>
				<Exception eps="0" p1="0" p2="1" q="0" sig="1"/>
				<Exception eps="0" p1="0" p2="2" q="0" sig="1"/>
				<Exception eps="0" p1="1" p2="2" q="0" sig="1"/>
				<Exception eps="0" p1="3" p2="4" q="0" sig="1"/>
				<Exception eps="0" p1="3" p2="5" q="0" sig="1"/>
				<Exception eps="0" p1="4" p2="5" q="0" sig="1"/>
			</Exceptions>
		</Force>
	</Forces>
</System>
```
is there a solution/workaround?

**Comment by jchodera** [comment]
I thought we were using SMIRNOFF's `openmmtools.typing.engines.ForceField` to assign TIP3P parameters using a SMIRNOFF `tip3p.xml` file.

**Comment by andrrizzi** [comment]
We are. This is a problem I run into while writing tests.

**Comment by jchodera** [comment]
Hm. The OpenMM [`tip3p.xml`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/data/tip3p.xml#L15-L17) *does* include bond parameters:
```
<ForceField>
 <AtomTypes>
  <Type name="tip3p-O" class="OW" element="O" mass="15.99943"/>
  <Type name="tip3p-H" class="HW" element="H" mass="1.007947"/>
 </AtomTypes>
 <Residues>
  <Residue name="HOH">
   <Atom name="O" type="tip3p-O"/>
   <Atom name="H1" type="tip3p-H"/>
   <Atom name="H2" type="tip3p-H"/>
   <Bond atomName1="O" atomName2="H1"/>
   <Bond atomName1="O" atomName2="H2"/>
  </Residue>
 </Residues>
 <HarmonicBondForce>
  <Bond class1="OW" class2="HW" length="0.09572" k="462750.4"/>
 </HarmonicBondForce>
 <HarmonicAngleForce>
  <Angle class1="HW" class2="OW" class3="HW" angle="1.82421813418" k="836.8"/>
 </HarmonicAngleForce>
 <NonbondedForce coulomb14scale="0.833333" lj14scale="0.5">
  <Atom type="tip3p-O" charge="-0.834" sigma="0.31507524065751241" epsilon="0.635968"/>
  <Atom type="tip3p-H" charge="0.417" sigma="1" epsilon="0"/>
 </NonbondedForce>
</ForceField>
```

**Comment by andrrizzi** [comment]
Yep! But I think they are added to the System only if `rigidWater=False`.

**Comment by jchodera** [comment]
Ah, true!

**Comment by davidlmobley** [comment]
We've run into this same issue. What's the easiest way to fix? Presumably we should just be adjusting the code to always add these to the system, rather than only for specific `rigidWater` cases?

**Comment by swails** [comment]
The core of the problem here is that those bond parameters are not actually stored in the System XML file.  As a result, ParmEd doesn't extract them.  The actual keyword that matters here is not really `rigidWater`, but rather `flexibleConstraints`.  That is the keyword that controls whether or not constraint parameters are added to the system.

I'm not sure where (or if) OpenMM exposes that in the public API (I'm pretty sure it *doesn't* in the Amber and CHARMM parsers).  ParmEd's structures *do* expose that keyword, and I'm pretty sure that if you use it, the generated `System` XML files will contain the necessary parameters.

So the options here are:

1. Submit a PR to OpenMM to expose `flexibleConstraints` as an input parameter to the `createSystem` method (note that `ForceField.createSystem` doesn't have this keyword, and the code to implement it would need to be added).
2. Use ParmEd to create the systems (doesn't work for PDB files)
3. Modify ParmEd to add some default parameters to constrained bonds whose parameters are not added to the System XML file.

**Comment by swails** [comment]
cc pandegroup/openmm#1823

**Comment by jchodera** [comment]
Did we ever figure out what to do with this?

**Comment by davidlmobley** [comment]
I don't think we have a general solution yet, partly because a solution would have just resulted in other problems further along the pipeline, @jchodera . Specifically, if you are currently creating a system containing water with SMIRNOFF and using ParmEd to write to AMBER format, there are problems with the resulting file sizes due to waters being mapped to SMIRKS patterns in differing orders, so fixing this specific issue still results in not being able to use systems solvated with water after output by ParmEd. As long as you stay in OpenMM there is no problem.

(I believe I have dealt with it once by adding dummy bonds within the waters.)
