### ISSUE TITLE
test/files/state_974wat.xml does not contain potential energy

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#906]
It looks like `test/files/state_974wat.xml` is used to test `parmed.openmm.xmlfile` in [this test](https://github.com/ParmEd/ParmEd/blob/master/test/test_parmed_openmm.py#L60), but this serialized `State` doesn't have a potential energy tag.

On my system with the `openmm` 7.2 `dev` build, this test triggers the following test failure:
```
======================================================================
ERROR: Tests automatic deserialization of a State XML file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/github/parmed/ParmEd/test/test_parmed_openmm.py", line 65, in test_deserialize_state
    state = openmm.XmlFile.parse(get_fn('state_974wat.xml'))
  File "/Users/choderaj/github/parmed/ParmEd/parmed/utils/decorators.py", line 31, in new_fcn
    return fcn(*args, **kwargs)
  File "/Users/choderaj/github/parmed/ParmEd/parmed/openmm/xmlfile.py", line 99, in parse
    return _OpenMMStateContents(obj)
  File "/Users/choderaj/github/parmed/ParmEd/parmed/openmm/xmlfile.py", line 155, in __init__
    u.kilocalorie_per_mole)
  File "/Users/choderaj/github/parmed/ParmEd/parmed/openmm/xmlfile.py", line 136, in _get_data
    stuff = getattr(state, getter)(**kwargs)
  File "/Users/choderaj/miniconda3/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18371, in getPotentialEnergy
    val = _openmm.State_getPotentialEnergy(self)
Exception: Invoked getPotentialEnergy() on a State which does not contain energies.
```
The [`_get_data`](https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/xmlfile.py#L133-L143) method is supposed to catch a `TypeError` and return `None` if this fails, but it looks like it's failing with an `Exception` on my system. Not sure why this doesn't happen on travis, but it might have something to do with the OpenMM dev build or that I'm using `osx`.

**Comment by jchodera** [comment]
I can confirm that this test passes with OpenMM 7.1.1 but fails with the OpenMM 7.2 dev build because the exception type appears to have changed.

**Comment by jchodera** [comment]
Actually, this sounds like a bug on the OpenMM side.

**Comment by jchodera** [comment]
This is an OpenMM issue: https://github.com/pandegroup/openmm/issues/1916
