### ISSUE TITLE
Using Multiple CHARMM parameter files 

### ISSUE THREAD

**Issue by leelasd** [ParmEd/ParmEd#970]
Hi @swails 

I have tried reading two different CHARMM parameter files with same NONBONDED settings but I got an error saying 

```
Traceback (most recent call last):
  File "/Users/Sriram/anaconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py", line 81, in _convert
    return type(data)
ValueError: could not convert string to float: 'ctofnb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Sriram/anaconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py", line 614, in read_parameter_file
    epsilon = conv(words[2], float, 'vdW epsilon term')
  File "/Users/Sriram/anaconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py", line 83, in _convert
    raise CharmmError('Could not convert %s to %s' % (msg, type))
parmed.exceptions.CharmmError: Could not convert vdW epsilon term to <class 'float'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "OpenMM_GBSA.py", line 16, in <module>
    params = CharmmParameterSet('parmed_par_opls_aam.inp','UFP_new.prm')
  File "/Users/Sriram/anaconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py", line 114, in __init__
    for par in pars: self.read_parameter_file(par)
  File "/Users/Sriram/anaconda3/lib/python3.5/site-packages/parmed/charmm/parameters.py", line 637, in read_parameter_file
    raise CharmmError('Inconsistent 1-4 '
parmed.exceptions.CharmmError: Inconsistent 1-4 scalings
```

When I looked at the Parmed  charmm/parameters.py, I realized that you are comparing inverse of scale factor with the scale factor. When I fixed it Parmed Works fine. 
```
diff = abs(dt0[0].scee - scee) ## It works fine when I change this to abs(dt0[0].scee - 1.0/scee)
if diff > TINY:
      raise CharmmError('Inconsistent 1-4 scalings')
 ```

I just want to confirm with you if this makes sense or not.

**Comment by swails** [comment]
Makes sense to me.  Can you raise a PR for this?
